apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodbuddy
  namespace: foodbuddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodbuddy
  template:
    metadata:
      labels:
        app: foodbuddy
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: foodbuddy
          image: lijuthomas/foodbuddy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: foodbuddy-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: foodbuddy
  namespace: foodbuddy
spec:
  selector:
    app: foodbuddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

