apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: foodbuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: foodbuddy-secrets
              key: DBPASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: foodbuddy-secrets
              key: DBNAME
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: foodbuddy-secrets
              key: DBUSER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: foodbuddy-secrets
              key: DBPASSWORD
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: foodbuddy
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
